set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)
set(VCPKG_OSX_DEPLOYMENT_TARGET 12.0)
set(VCPKG_BUILD_TYPE release)

# 同时写入编译参数，覆盖没有读取 VCPKG_OSX_DEPLOYMENT_TARGET 的旧端口。
set(VCPKG_C_FLAGS "-mmacosx-version-min=12.0")
set(VCPKG_CXX_FLAGS "-mmacosx-version-min=12.0")
